version: "3"
services:
  web:
    build: .
    volumes:
      - ./app:/workspace
    ports:
      - 80:80
    environment:
      - FLASK_APP=/workspace/app.py
    command: flask run --host 0.0.0.0 --port 80
